name: moviebox
description: A movie application using TMDB API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'  # Updated for Dart 3.6.1

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  http: ^0.13.5
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6  # Ensure this line exists
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true